apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - kubernetes
    - aws-eks
    - rest
  links:
    - title: health status
      ### DATA_PLANE_LB needs to be configured and plugged in
      url: https://a20df726a16ea4cbdb91c30c2f82a6b2-1628815465.ap-southeast-2.elb.amazonaws.com/${{ values.component_id }}/actuator/health
      icon: dashboard
      ### domain name needs to be configured
    - title: kong manager
      url: http://a3f9fd27125c640cc8ce3f1d4f2ae5b0-1987737800.ap-southeast-2.elb.amazonaws.com:8002/overview
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id}}
#  consumesApis:
#    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/src/main/resources/api-docs.yaml
