apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: src/main/resources/api-docs.yaml
