apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{values.artifact_id}}
  name: ${{values.artifact_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.artifact_id}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${{values.artifact_id}}
    spec:
      containers:
      - image: ${{ values.owner }}/${{values.artifact_id}}
        name: ${{values.artifact_id}}
