apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-service-complete
  name: rest-service-complete
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-service-complete
  type: ClusterIP
status:
  loadBalancer: {}
