apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{values.artifact_id}}
  name: ${{values.artifact_id}}
spec:
  ports:
  - name: ${{values.http_port}}-${{values.http_port}}
    port: ${{values.http_port}}
    targetPort: ${{values.http_port}}
  selector:
    app: ${{values.artifact_id}}
  type: ClusterIP
